#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Alpha >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.Alpha=/luci-static/alpha
		set luci.main.mediaurlbase=/luci-static/alpha
		commit luci
	EOF
fi

exit 0
