name: Build single OpenWrt package

on:
  workflow_dispatch: # jalan manual
  push:
    branches:
      - Alpha-OS-4.0-Beta-(for-OpenWrt-24.xx)

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
            gettext git java-propose-classpath libncurses5-dev libssl-dev python3 \
            python3-distutils unzip wget zlib1g-dev

      - name: Download OpenWrt SDK
        run: |
          wget https://downloads.openwrt.org/releases/23.05.2/targets/x86/64/openwrt-sdk-23.05.2-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk-*.tar.xz
          mv openwrt-sdk-* openwrt-sdk

      - name: Copy package
        run: |
          mkdir -p openwrt-sdk/package/custom
          cp -r ./luci-app-myapp openwrt-sdk/package/custom/

      - name: Build package
        run: |
          cd openwrt-sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make package/custom/luci-app-alpha4/compile V=s

      - name: Upload ipk
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-alpha4
          path: openwrt-sdk/bin/packages/**/*.ipk
